In [32]:
import pandas as pd
from cdapython import tables, columns, column_values, fetch_rows, summary_counts

Query = {'match_any': ['primary_diagnosis_site = *cerv*',
                       'primary_diagnosis_site = *uter*'],
         'data_source': 'GDC'}
# data_source='GDC'
subject = fetch_rows( table='subject', match_any=["primary_diagnosis_site = *thyroid*"], # "primary_diagnosis_site = *thyroidal*" 
                     data_source = 'GDC',
                     provenance=True) # provenance=True data_source='GDC', 

#subject = fetch_rows( table='subject', match_any=["primary_diagnosis_site = *brain*","primary_diagnosis_site = *cerebral*"], provenance=True) # provenance=True

#['primary_diagnosis_site = *brain*',
#                       'primary_diagnosis_site = *cerebral*']
#subject = subject.drop(columns=['subject_data_source_id'], axis=1)

# 2832 rows Ã— 11 columns
subject

,subject_id,cause_of_death,days_to_birth,days_to_death,ethnicity,race,sex,species,vital_status,subject_data_source,subject_data_source_id
0,FM.AD1008,,<NA>,<NA>,,,female,human,,GDC,case.submitter_id:AD1008
1,FM.AD1016,,<NA>,<NA>,,,male,human,,GDC,case.submitter_id:AD1016
2,FM.AD10209,,<NA>,<NA>,,,female,human,,GDC,case.submitter_id:AD10209
3,FM.AD10222,,<NA>,<NA>,,,female,human,,GDC,case.submitter_id:AD10222
4,FM.AD10308,,<NA>,<NA>,,,female,human,,GDC,case.submitter_id:AD10308
...,...,...,...,...,...,...,...,...,...,...,...
2827,TCGA.TCGA-MK-A84Z,,-27185,<NA>,Non-Hispanic,Black or African American,male,human,Alive,IDC,submitter_case_id:TCGA-MK-A84Z
2828,TCGA.TCGA-QD-A8IV,,-18288,<NA>,Non-Hispanic,Black or African American,female,human,Alive,GDC,case.submitter_id:TCGA-QD-A8IV
2829,TCGA.TCGA-QD-A8IV,,-18288,<NA>,Non-Hispanic,Black or African American,female,human,Alive,IDC,idc_case_id:bbb9102f-695e-47b0-9b5f-4c8ecd5f380a
2830,TCGA.TCGA-QD-A8IV,,-18288,<NA>,Non-Hispanic,Black or African American,female,human,Alive,IDC,PatientID:TCGA-QD-A8IV
2831,TCGA.TCGA-QD-A8IV,,-18288,<NA>,Non-Hispanic,Black or African American,female,human,Alive,IDC,submitter_case_id:TCGA-QD-A8IV

In [34]:
researchsub = fetch_rows(table='researchsubject', match_any=["primary_diagnosis_site = *thyroid*"], # "primary_diagnosis_site = *thyroidal*" 
                         provenance=True) # data_source = 'GDC',add_columns=['subject_id']
# 3938 rows Ã— 6 columns
researchsub

,researchsubject_id,member_of_research_project,primary_diagnosis_condition,primary_diagnosis_site,researchsubject_data_source,researchsubject_data_source_id
0,FM-AD.AD1008,FM-AD,Squamous Cell Neoplasms,thyroid gland,GDC,case.case_id:b9e3dc0d-a4e1-45e2-8532-6af921d41f55
1,FM-AD.AD1008,FM-AD,Squamous Cell Neoplasms,thyroid gland,GDC,case.submitter_id:AD1008
2,FM-AD.AD1016,FM-AD,Squamous Cell Neoplasms,thyroid gland,GDC,case.case_id:3d9bdc0d-7920-4fe3-a958-7f85e5c27e59
3,FM-AD.AD1016,FM-AD,Squamous Cell Neoplasms,thyroid gland,GDC,case.submitter_id:AD1016
4,FM-AD.AD10209,FM-AD,"Epithelial Neoplasms, NOS",thyroid gland,GDC,case.case_id:95ba7ce2-2430-4273-8b65-f1317f3e2293
...,...,...,...,...,...,...
3933,tcga_thca.TCGA-QD-A8IV.RS,tcga_thca,Thyroid Cancer,thyroid gland,IDC,PatientID:TCGA-QD-A8IV
3934,tcga_thca.TCGA-QD-A8IV.RS,tcga_thca,Thyroid Cancer,thyroid gland,IDC,submitter_case_id:TCGA-QD-A8IV
3935,TCL01.TCL01-CTAC,TCL01,Thyroid Cancer,thyroid gland,ICDC,case.case_id:TCL01-CTAC
3936,TCL01.TCL01-CTAC,TCL01,Thyroid Cancer,thyroid gland,ICDC,case.patient_id:CTAC
3937,TCL01.TCL01-CTAC,TCL01,Thyroid Cancer,thyroid gland,ICDC,enrollment.enrollment_id:TCL01-CTAC

In [22]:
sub_rsub_df = subject.merge(researchsub, on='subject_id', how='outer')
sub_rsub_df

,subject_id,cause_of_death,days_to_birth,days_to_death,ethnicity,race,sex,species,vital_status,subject_data_source,subject_data_source_id,researchsubject_id,member_of_research_project,primary_diagnosis_condition,primary_diagnosis_site
0,CCDI.PBBPBM,,575268,<NA>,Non-Hispanic,White,female,human,,CDS,participant.participant_id:PBBPBM,phs002790.PBBPBM,phs002790,Embryonal sarcoma,liver
1,CCDI.PBBPBM,,575268,<NA>,Non-Hispanic,White,female,human,,CDS,participant.uuid:e1d3f69d-b1aa-5b16-887c-69757...,phs002790.PBBPBM,phs002790,Embryonal sarcoma,liver
2,CCDI.PBBPDR,,2344539,<NA>,Non-Hispanic,White,male,human,,CDS,participant.participant_id:PBBPDR,phs002790.PBBPDR,phs002790,"Sarcoma, NOS",liver
3,CCDI.PBBPDR,,2344539,<NA>,Non-Hispanic,White,male,human,,CDS,participant.uuid:371ca024-d2ad-51c3-b270-49a06...,phs002790.PBBPDR,phs002790,"Sarcoma, NOS",liver
4,CCDI.PBBPRD,,1326588,<NA>,Hispanic or Latino,White,male,human,,CDS,participant.participant_id:PBBPRD,phs002790.PBBPRD,phs002790,"Neoplasm, malignant, uncertain whether primary...",liver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2904,hcc_tace_seg.HCC_104,,<NA>,<NA>,,,,human,,IDC,PatientID:HCC_104,hcc_tace_seg.HCC_104.RS,hcc_tace_seg,Hepatocellular carcinoma,liver
2905,hcc_tace_seg.HCC_104,,<NA>,<NA>,,,,human,,IDC,submitter_case_id:HCC_104,hcc_tace_seg.HCC_104.RS,hcc_tace_seg,Hepatocellular carcinoma,liver
2906,hcc_tace_seg.HCC_105,,<NA>,<NA>,,,,human,,IDC,idc_case_id:9d1cce6d-2831-4198-834a-d5f400dfbe95,hcc_tace_seg.HCC_105.RS,hcc_tace_seg,Hepatocellular carcinoma,liver
2907,hcc_tace_seg.HCC_105,,<NA>,<NA>,,,,human,,IDC,PatientID:HCC_105,hcc_tace_seg.HCC_105.RS,hcc_tace_seg,Hepatocellular carcinoma,liver
2908,hcc_tace_seg.HCC_105,,<NA>,<NA>,,,,human,,IDC,submitter_case_id:HCC_105,hcc_tace_seg.HCC_105.RS,hcc_tace_seg,Hepatocellular carcinoma,liver

In [23]:
sites = column_values(column='primary_diagnosis_site')
#sites.shape
sites

          primary_diagnosis_site  count
0                                 66419
1                          chest  28221
2                         breast  21203
3                           lung  12289
4                  immune system   9029
..                           ...    ...
149                sigmoid colon      1
150                skin of trunk      1
151          submandibular gland      1
152  supraglottic part of larynx      1
153                      urachus      1

[154 rows x 2 columns]

In [6]:
import pandas as pd
site_to_uberon = pd.read_csv("../src/oncopacket/ncit_mapping_files/CDA_primary_diagnosis_site_to_uberon.csv")
_site_to_uberon_label_d = dict(site_to_uberon.values)

_site_to_uberon_label_d.get('appendicular skeleton')

'UBERON:0002091'

In [9]:
stages = column_values(column='stage')
stages

            stage   count
0                  117106
1             III     503
2       Stage IIA     410
3      Stage IIIC     346
4        Stage II     189
5      Stage IIIA     169
6       Stage IIB     159
7      Stage IIIB     141
8        Stage IA     117
9         Stage I     113
10             IV     103
11       Stage IV      93
12             M0      92
13             IA      88
14      Stage III      87
15         T2N0M0      64
16             IB      63
17             II      62
18             M3      52
19       Stage IB      41
20           IIIa      40
21         Stage1      28
22      Stage IVA      21
23             M1      20
24         T3N0M0      17
25           IIIA      16
26            IIb      13
27            IIA       8
28             Ia       8
29             M2       8
30       Stage IC       8
31            IVa       7
32   Not Received       5
33         T2N1M0       5
34           pT3a       5
35              V       4
36             Va       4
37            IVb       3
38  Not Performed       3
39         T3N0M1       3
40              I       2
41            IIB       2
42         T2N0M1       2
43         T3N1M0       2
44           IIIB       1
45           IIIb       1
46         T2N1M1       1
47         T2N2M1       1
48         T3N1M1       1
49        TisN1M1       1
50             Vb       1
51            pT1       1
52           pT1a       1
53           pT1b       1
54            pT4       1