In [1]:
import pandas as pd
from cdapython import tables, columns, column_values, fetch_rows, summary_counts

Query = {'match_any': ['primary_diagnosis_site = *colon*'],
         'data_source': 'GDC'}
# data_source='GDC'
subject = fetch_rows( table='subject', match_any=["primary_diagnosis_site = *colon*"], # "primary_diagnosis_site = *thyroidal*" 
                     data_source='GDC', provenance=True) # provenance=True data_source='GDC', 

#subject = fetch_rows( table='subject', match_any=["primary_diagnosis_site = *brain*","primary_diagnosis_site = *cerebral*"], provenance=True) # provenance=True

#['primary_diagnosis_site = *brain*',
#                       'primary_diagnosis_site = *cerebral*']
#subject = subject.drop(columns=['subject_data_source_id'], axis=1)

# 2832 rows Ã— 11 columns
subject

,subject_id,cause_of_death,days_to_birth,days_to_death,ethnicity,race,sex,species,vital_status,subject_data_source,subject_data_source_id
0,CPTAC.01CO001,,<NA>,<NA>,Non-Hispanic,White,male,human,,GDC,case.submitter_id:01CO001
1,CPTAC.01CO001,,<NA>,<NA>,Non-Hispanic,White,male,human,,IDC,idc_case_id:c237122e-069c-4184-935b-de48b5ba9dd9
2,CPTAC.01CO001,,<NA>,<NA>,Non-Hispanic,White,male,human,,IDC,PatientID:01CO001
3,CPTAC.01CO001,,<NA>,<NA>,Non-Hispanic,White,male,human,,IDC,submitter_case_id:01CO001
4,CPTAC.01CO001,,<NA>,<NA>,Non-Hispanic,White,male,human,,PDC,Case.case_id:8d8d42ae-63d5-11e8-bcf1-0a2705229b82
...,...,...,...,...,...,...,...,...,...,...,...
4927,TCGA.TCGA-T9-A92H,,-30058,<NA>,Non-Hispanic,Black or African American,male,human,Alive,IDC,submitter_case_id:TCGA-T9-A92H
4928,TCGA.TCGA-WS-AB45,,<NA>,<NA>,Non-Hispanic,Black or African American,female,human,Alive,GDC,case.submitter_id:TCGA-WS-AB45
4929,TCGA.TCGA-WS-AB45,,<NA>,<NA>,Non-Hispanic,Black or African American,female,human,Alive,IDC,idc_case_id:95437d67-fb69-402a-b216-86dc45c34f21
4930,TCGA.TCGA-WS-AB45,,<NA>,<NA>,Non-Hispanic,Black or African American,female,human,Alive,IDC,PatientID:TCGA-WS-AB45
4931,TCGA.TCGA-WS-AB45,,<NA>,<NA>,Non-Hispanic,Black or African American,female,human,Alive,IDC,submitter_case_id:TCGA-WS-AB45

In [7]:
subject = fetch_rows( table='subject', match_any=["subject_id = TCGA.TCGA-AG-3881"],
                     add_columns=['primary_diagnosis_site'])
subject

,subject_id,cause_of_death,days_to_birth,days_to_death,ethnicity,race,sex,species,vital_status,researchsubject_id,primary_diagnosis_site
0,TCGA.TCGA-AG-3881,,-30467,<NA>,,,female,human,Alive,phs003155.TCGA-AG-3881,
1,TCGA.TCGA-AG-3881,,-30467,<NA>,,,female,human,Alive,TCGA-READ.TCGA-AG-3881,
2,TCGA.TCGA-AG-3881,,-30467,<NA>,,,female,human,Alive,tcga_read.TCGA-AG-3881.RS,rectum

In [9]:
rsub = fetch_rows( table='researchsubject', match_any=["subject_id = TCGA.TCGA-AG-3881"])
rsub

,researchsubject_id,member_of_research_project,primary_diagnosis_condition,primary_diagnosis_site
0,phs003155.TCGA-AG-3881,phs003155,Neoplasm,
1,TCGA-READ.TCGA-AG-3881,TCGA-READ,"Cystic, Mucinous and Serous Neoplasms",
2,tcga_read.TCGA-AG-3881.RS,tcga_read,Rectum Adenocarcinoma,rectum

In [2]:
researchsub = fetch_rows(table='researchsubject', match_any=["primary_diagnosis_site = *colon*"], # "primary_diagnosis_site = *thyroidal*" 
                         data_source = 'GDC',
                         provenance=True) # data_source = 'GDC',add_columns=['subject_id']
# 3938 rows Ã— 6 columns
researchsub

,researchsubject_id,member_of_research_project,primary_diagnosis_condition,primary_diagnosis_site,researchsubject_data_source,researchsubject_data_source_id
0,CPTAC-2.01CO001,CPTAC-2,Adenomas and Adenocarcinomas,colon,GDC,case.case_id:9705a94f-8707-46f5-a25a-aa746dc323a6
1,CPTAC-2.01CO001,CPTAC-2,Adenomas and Adenocarcinomas,colon,GDC,case.submitter_id:01CO001
2,CPTAC-2.01CO005,CPTAC-2,Adenomas and Adenocarcinomas,colon,GDC,case.case_id:4c640f79-0207-4cc1-9792-19ea34b35f3d
3,CPTAC-2.01CO005,CPTAC-2,Adenomas and Adenocarcinomas,colon,GDC,case.submitter_id:01CO005
4,CPTAC-2.01CO006,CPTAC-2,Adenomas and Adenocarcinomas,colon,GDC,case.case_id:143daf5b-2378-4b5c-888c-43a6c802fbc9
...,...,...,...,...,...,...
5005,TCGA-READ.TCGA-AG-4008,TCGA-READ,Adenomas and Adenocarcinomas,colon,GDC,case.submitter_id:TCGA-AG-4008
5006,TCGA-READ.TCGA-AG-4015,TCGA-READ,Adenomas and Adenocarcinomas,colon,GDC,case.case_id:1388bba1-02ba-40df-93e5-c3d58b7bbae0
5007,TCGA-READ.TCGA-AG-4015,TCGA-READ,Adenomas and Adenocarcinomas,colon,GDC,case.submitter_id:TCGA-AG-4015
5008,TCGA-SARC.TCGA-DX-AB35,TCGA-SARC,Lipomatous Neoplasms,colon,GDC,case.case_id:e9e4731a-a7ca-455c-868c-a6d53d0aa749
5009,TCGA-SARC.TCGA-DX-AB35,TCGA-SARC,Lipomatous Neoplasms,colon,GDC,case.submitter_id:TCGA-DX-AB35

In [22]:
sub_rsub_df = subject.merge(researchsub, on='subject_id', how='outer')
sub_rsub_df

,subject_id,cause_of_death,days_to_birth,days_to_death,ethnicity,race,sex,species,vital_status,subject_data_source,subject_data_source_id,researchsubject_id,member_of_research_project,primary_diagnosis_condition,primary_diagnosis_site
0,CCDI.PBBPBM,,575268,<NA>,Non-Hispanic,White,female,human,,CDS,participant.participant_id:PBBPBM,phs002790.PBBPBM,phs002790,Embryonal sarcoma,liver
1,CCDI.PBBPBM,,575268,<NA>,Non-Hispanic,White,female,human,,CDS,participant.uuid:e1d3f69d-b1aa-5b16-887c-69757...,phs002790.PBBPBM,phs002790,Embryonal sarcoma,liver
2,CCDI.PBBPDR,,2344539,<NA>,Non-Hispanic,White,male,human,,CDS,participant.participant_id:PBBPDR,phs002790.PBBPDR,phs002790,"Sarcoma, NOS",liver
3,CCDI.PBBPDR,,2344539,<NA>,Non-Hispanic,White,male,human,,CDS,participant.uuid:371ca024-d2ad-51c3-b270-49a06...,phs002790.PBBPDR,phs002790,"Sarcoma, NOS",liver
4,CCDI.PBBPRD,,1326588,<NA>,Hispanic or Latino,White,male,human,,CDS,participant.participant_id:PBBPRD,phs002790.PBBPRD,phs002790,"Neoplasm, malignant, uncertain whether primary...",liver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2904,hcc_tace_seg.HCC_104,,<NA>,<NA>,,,,human,,IDC,PatientID:HCC_104,hcc_tace_seg.HCC_104.RS,hcc_tace_seg,Hepatocellular carcinoma,liver
2905,hcc_tace_seg.HCC_104,,<NA>,<NA>,,,,human,,IDC,submitter_case_id:HCC_104,hcc_tace_seg.HCC_104.RS,hcc_tace_seg,Hepatocellular carcinoma,liver
2906,hcc_tace_seg.HCC_105,,<NA>,<NA>,,,,human,,IDC,idc_case_id:9d1cce6d-2831-4198-834a-d5f400dfbe95,hcc_tace_seg.HCC_105.RS,hcc_tace_seg,Hepatocellular carcinoma,liver
2907,hcc_tace_seg.HCC_105,,<NA>,<NA>,,,,human,,IDC,PatientID:HCC_105,hcc_tace_seg.HCC_105.RS,hcc_tace_seg,Hepatocellular carcinoma,liver
2908,hcc_tace_seg.HCC_105,,<NA>,<NA>,,,,human,,IDC,submitter_case_id:HCC_105,hcc_tace_seg.HCC_105.RS,hcc_tace_seg,Hepatocellular carcinoma,liver

In [23]:
sites = column_values(column='primary_diagnosis_site')
#sites.shape
sites

          primary_diagnosis_site  count
0                                 66419
1                          chest  28221
2                         breast  21203
3                           lung  12289
4                  immune system   9029
..                           ...    ...
149                sigmoid colon      1
150                skin of trunk      1
151          submandibular gland      1
152  supraglottic part of larynx      1
153                      urachus      1

[154 rows x 2 columns]

In [6]:
import pandas as pd
site_to_uberon = pd.read_csv("../src/oncopacket/ncit_mapping_files/CDA_primary_diagnosis_site_to_uberon.csv")
_site_to_uberon_label_d = dict(site_to_uberon.values)

_site_to_uberon_label_d.get('appendicular skeleton')

'UBERON:0002091'

In [9]:
stages = column_values(column='stage')
stages

            stage   count
0                  117106
1             III     503
2       Stage IIA     410
3      Stage IIIC     346
4        Stage II     189
5      Stage IIIA     169
6       Stage IIB     159
7      Stage IIIB     141
8        Stage IA     117
9         Stage I     113
10             IV     103
11       Stage IV      93
12             M0      92
13             IA      88
14      Stage III      87
15         T2N0M0      64
16             IB      63
17             II      62
18             M3      52
19       Stage IB      41
20           IIIa      40
21         Stage1      28
22      Stage IVA      21
23             M1      20
24         T3N0M0      17
25           IIIA      16
26            IIb      13
27            IIA       8
28             Ia       8
29             M2       8
30       Stage IC       8
31            IVa       7
32   Not Received       5
33         T2N1M0       5
34           pT3a       5
35              V       4
36             Va       4
37            IVb       3
38  Not Performed       3
39         T3N0M1       3
40              I       2
41            IIB       2
42         T2N0M1       2
43         T3N1M0       2
44           IIIB       1
45           IIIb       1
46         T2N1M1       1
47         T2N2M1       1
48         T3N1M1       1
49        TisN1M1       1
50             Vb       1
51            pT1       1
52           pT1a       1
53           pT1b       1
54            pT4       1